version: '3.9'
services:
  app:
    image: springboot
    ports:
      - "8090:8080"
    depends_on:
      - database
      - rabbitmq
      - fakesmtp
    links:
      -redis
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://database:3306/employee_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Gandhi@123
      
     
    
      
     
  database:
    image: mysql:latest
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: Gandhi@123
      MYSQL_DATABASE: employee_db
    ports:
      - "3307:3306"
  rabbitmq:
    image: rabbitmq
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest
    ports:
      - "5672:5672"
  redis:
    image: redis
    
    ports:
      - "6379:6379"
  fakesmtp:
    image: djfarrelly/maildev
    ports:
      - "25:25"
    environment:
      - EMAIL_STORAGE=/var/mail
      
