version: "3.9"

services:
  mysql:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: Gandhi@123
      MYSQL_DATABASE: employee_db
    ports:
      - "3307:3306"
  redis:
    image: redis
    ports:
      - "6379:6379"
  fakesmtp:
    image: djfarrelly/maildev
    ports:
      - "25:25"
    environment:
      SPRING_MAIL_HOST: fakesmtp
      SPRING_MAIL_PORT: 25
      SPRING_MAIL_USERNAME: demo@localhost
      SPRING_MAIL_PASSWORD: demopassword
      SPRING_CACHE_REDIS_CACHE-NULL-VALUES: "true"
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE: "false"
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH: "true"
      SPRING_MAIL_PROPERTIES_MAIL_TRANSPORT_PROTOCOL: smtp
      SPRING_MAIL_PROPERTIES_MAIL_SMTPS_QUITWAIT: "false"
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_SOCKETFACTORY_PORT: 465
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_SOCKETFACTORY_CLASS: javax.net.ssl.SSLSocketFactory
  rabbitmq:
      image: rabbitmq:latest
      ports:
        - "5672:5672"
      environment:
        SPRING_RABBITMQ_HOST: rabbitmq
        SPRING_RABBITMQ_PORT: 5672
        SPRING_RABBITMQ_USERNAME: guest
        SPRING_RABBITMQ_PASSWORD: guest
  app:
    image: springboot
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mysql
      #- redis
    ports:
      - "8090:8080"
    links:
      - redis
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://database:3306/employee_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Gandhi@123
    #   REDIS_HOST: redis
    #  REDIS_PORT: 6379
