apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-app-ingress
  annotations:
  # Add your desired annotations here
spec:
  rules:
    - host: my-app.example.com
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: employeechart
                port:
                  number: 8080