
image:
  repository: suveetha/springboot
  pullPolicy: IfNotPresent
  tag: latest


service:
  type: ClusterIP

spring:
  datasource:
    url: jdbc:mysql://mysql:3306/employee_db
    username: root
    password: Gandhi@123

rabbitmq:
  host: rabbitmq
  port: 5672
  queue:
    name: department-queue
    durable: true
  exchange:
    name: department-exchange
  binding:
    routingKey: myRoutingKey

mysql:
  rootPassword: "Gandhi@123"
  database: "employee_db"

ingress:
  enabled: true
  annotations:
  # Add your desired annotations here
  hosts:
    - host: my-app.example.com
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
serviceAccount:
  create: true

autoscaling:
  enabled: false
